# Generated by Django 5.2.3 on 2025-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userdata_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='door_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='zipcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
