# Generated by Django 5.2.3 on 2025-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.CharField(max_length=200)),
                ('defect_name', models.CharField(max_length=200)),
                ('assignedby', models.CharField(max_length=200)),
                ('assignedto', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=50)),
            ],
        ),
    ]
