# Generated by Django 5.2.3 on 2025-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
