# Generated by Django 5.2.3 on 2025-08-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_defect_defect_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='defect',
            new_name='defectid',
        ),
    ]
