# Generated by Django 5.2.3 on 2025-08-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_rename_defect_defect_defectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='defect_screen_short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('defect_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.defect')),
            ],
        ),
    ]
