# Generated by Django 5.2.3 on 2025-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_defect_screen_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect_screen_short',
            name='defect_img',
            field=models.ImageField(blank=True, null=True, upload_to='defects/'),
        ),
    ]
