# Generated by Django 5.2.3 on 2025-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0005_alter_defect_screen_short_defect_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_edit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
